### ISSUE TITLE
انتخاب ریل

### ISSUE THREAD

**Issue by mehrdad2** [ronack/silent#1]
در صورت انتخاب: عرض پشت تا پشت ریل نمایش داده شود(ریل میخواهد)
 در صورت انتخاب عرض برش ریل ها نمایش داده نشود(ریل نمی خواهد)

**Comment by mostafaznv** [comment]
توی 2 نسخه قبل انجام شده

**Comment by mehrdad2** [comment]
بر عکس انجام شده

**Comment by mostafaznv** [comment]
انجام شد
فایل iscript.js رو از کش در بیار

**Comment by mehrdad2** [comment]
دستت بی بلا اینش اوکی شده اما مرحله بعدش هنوز جا به جاست یا سیستم من مشکل داره؟

**Comment by mostafaznv** [comment]
مرحله بعدش كدومه؟
فكر كنم همه ش رو اوكي كرده باشم

**Comment by mehrdad2** [comment]
الان من تو مرحله دوم میگذارم روی عرض پشت تا پشت که ریل میخواد
تو مرحله بعد رنگ ریل از من نمی خواد

**Comment by mehrdad2** [comment]
![1](https://cloud.githubusercontent.com/assets/4264683/21213867/725268a8-c2ac-11e6-9954-8da2a51010d8.png)
![2](https://cloud.githubusercontent.com/assets/4264683/21213877/7aa53652-c2ac-11e6-9b0e-2c81c504683c.png)

**Comment by mostafaznv** [comment]
به نظر میرسه که الان دیگه مشکل برطرف شده باشه

**Comment by mehrdad2** [comment]
دقیقا درسته - دستت  بی بلا مهندس گل - عالیه - ایول

**Comment by mostafaznv** [comment]
مخلصم
