### ISSUE TITLE
ثبت نام - لاگین

### ISSUE THREAD

**Issue by mehrdad2** [ronack/silent#10]
فیلد های ثبت نام به شرح زیر است:
۱- نام
۲-نام خانوادگی
۳-شهر
۴-آدرس پستی
۵- تلفن تماس
--------------------
پس از ارسال اطلاعات فوق -برای اطلاعات لاگین توسط ادمین تعریف میشود
۱- نام کاربری 
۲- رمز عبور
--------------------
نام کاربری کدیست که برای هر کاربر توسط ادمین تعریف میشود
رمز عبور برای هر کاربر توسط ادمین تعریف میشود

**Comment by mostafaznv** [comment]
با این اوصاف مسائل ثبت نام و ورود و ... مشکل حاد و اساسی دارن.
کاربر ثبت نام میکنه اما اطلاعی از اطلاعات ورودش نداره!
باید تا زمانی که ادمین لاگین میشه صبر کنه ...

ادمین هم که لاگین میشه و واسه کاربر یوزر پسورد میسازه، اونم نمیدونه چطوری باید یوزر پسورد رو به دست کاربر برسونه که البته این وسط سیستم ارسال پیام کوتاه میتونه تقریبا مفید باشه...

اما در هر صورت آبکی ترین چیزیه که تابحال توی وب کار کردم.
اما از اونجایی که عواقبش به صورت 100 درصدی متوجه من نیست و متوجه مشتریه، انجامش میدم.
ممکنه کلا بخش فروش سایت بره روی هوا :))) اما اینا دیگه به ما مربوط نیست
