### ISSUE TITLE
نمایش نهایی رنگ ها

### ISSUE THREAD

**Issue by mehrdad2** [ronack/silent#3]
در نمایش نهایی رنگ ها:
۱-رنگ انتخابی ریل مشخص باشد
میتونه دو تا باکس ساده سمت راست و چپ باش
۲-هر کدام از تیغه ها مشخص شوند
به طور مثال یه بوردر ساده با رنگ خیلی محو 
۳- به طور کلی شبیه به درب کرکره ای شود

**Comment by mostafaznv** [comment]
موارد اعمال شد
