### ISSUE TITLE
ارتفاع تیغه در صورت ویرایش

### ISSUE THREAD

**Issue by mehrdad2** [ronack/silent#4]
ارتفاع تیغه حتی در صورت ویرایش تغییر نکرده و ثابت می ماند
![screen shot 2016-12-09 at 7 45 38 pm](https://cloud.githubusercontent.com/assets/4264683/21055867/76b04c3e-be48-11e6-81e1-86576de1a3de.png)

**Comment by mostafaznv** [comment]
انجام شد
