### ISSUE TITLE
پروسه خرید تغییر کند

### ISSUE THREAD

**Issue by mehrdad2** [ronack/silent#8]
تغییرات مربوط به پروسه خرید:

- [x] کاربر برای انتخاب تیغه رنگی یکسان مجبور به انتخاب مجدد رنگ تکراری نباشد

- [x] رنگ ها به صورت serachable دراپ داون باشد

- [x] امکان خرید ریل وجود داشته باشد.(به صورت مجزا)

- [x] فیلد های مربوط به ثبت نام تغییر کند(فیلد ها اعلام میگردد)

**Comment by mostafaznv** [comment]
در صورت امکان ریخت و قیافه searchable ها رو از مشتری تاییدیه بگیر و بهم بگو که چطوری باشن

**Comment by mostafaznv** [comment]
@mehrdad2 
شکل و ظاهر فاکتور خرید رو اوکی کن بهم برسون
![aa](https://cloud.githubusercontent.com/assets/7619687/23698801/35bace52-0402-11e7-880d-e85977308d19.png)
