### ISSUE TITLE
طرح پیشنهادی برای پروسه خرید

### ISSUE THREAD

**Issue by mehrdad2** [ronack/silent#9]
![slient_mockup1](https://cloud.githubusercontent.com/assets/4264683/23163791/3778bf34-f849-11e6-8a11-a1dc53d16658.png)
![slient_mockup2](https://cloud.githubusercontent.com/assets/4264683/23163792/37b5ecd8-f849-11e6-805a-3bc7aedcc91d.png)
![slient_mockup3](https://cloud.githubusercontent.com/assets/4264683/23163794/37e064c2-f849-11e6-8ddf-31d602134e50.png)

**Comment by mehrdad2** [comment]
@mostafaznv برای پیاده سازی اینا مشکلی نیست؟
بفرستم برای مشتری؟

**Comment by mostafaznv** [comment]
فقط رنگ تیغه فرعیه که این مدلی و به صورت داینامیک کانتنت انتخاب میشه؟
اگه دقیقا همین چیزیه که توی عکس ها هست و هیچ بند و تبصره دیگه ای نداره، به نظر قابل اجراست.
سخت هست! اما قابل اجراست
@mehrdad2

**Comment by mehrdad2** [comment]
اره ، اینکه کرکره هم آمده این صفحه مشکلی نیست؟
@mostafaznv

**Comment by mostafaznv** [comment]
شدنیه
فقط کار رو سخت میکنه
کلا این قسمت خریدش باید از نو نوشته بشه
